### ISSUE TITLE
User stories brain dump

### ISSUE THREAD

**Issue by jontg** [technologists-for-progress/52calls-52weeks#21]
iPad sign up at march/protest/whathaveyou boots on the ground — MVP
- sign up *at the rally* — this is _MVP_
  - name
  - email or phone (that can receive txts) [either/or, maybe both]
    * look into handling failed sms delivery
  - address
  - contact preference (text vs e-mail)
    - time zone captured by location from the form (at least by default?), `am / pm`
- Confirmation page driven by Civic Information [senators and reps]
- Get a welcome e-mail _and_/_or_ text
  - LIkely only one!
  - Confirm e-mail address to "register an account" ?
  - "1 to stop" type stuff for phone verification (registration code?)
- *INTERACTION MIGHT STOP AT THIS POINT* without "creating an account"
  - can we get away with _not_ creating an account at all?

Focus is specifically on national issues!

MailChimp???
  - We want "the issue of the week" driven by Katie
  - E-mail created by Katie every week [how does this get into the system]
  - can we just sync to mailchimp with... custom properties?
  - "I did this" button goes back through my systems
    - You just did democracy!

  - Can I *pull* SMS templates from mailchimp?

Trumpia???
  - http://trumpia.com/

Respond with "We did it!" or text back "done" to capture whether people did it!

Templates
  - Welcome,
  - Calls
  - Results!
    * Our community helped drive !!!

**Comment by sethvoltz** [comment]
Research:

- document API to add user record to MailChimp
- document API to extract read-email data
- Can MailChimp have a unique ID value in outgoing emails (or a campaign value auto-appended?) which we can track on Lambda/Gateway
- Destination page should have "Call Now" on mobile or "Show Number" popup (or something) for the final action.
- Texts should have a tracker link as well. ShortURL off the domain is helpful, or use 3rd party service we trust? https://52calls/abc123 to expand to same URL as email with text as source
- Nightly pull to sync "unsub" from MailChimp back to core

Tracking:

- Sent Emails/Texts count
- Read emails count
- Opened link count
- Calls / clicked to show number count

**Comment by jontg** [comment]
Mailchimp API seems to be pretty nice so far, except kinda judgemental about my e-mail address!
```
➜ curl -s -XPOST -H "Content-Type: application/json" -d '{"username": "jon", "password": "Test123", "email": "spam@ulfhedinn.net"}' https://f9b8mmc9w8.execute-api.us-west-2.amazonaws.com/dev/users/register | jq -r .errorMessage | jq .
{
  "status": "error",
  "code": -100,
  "name": "ValidationError",
  "error": "This email address looks fake or invalid. Please enter a real email address."
}```

**Comment by jontg** [comment]
https://github.com/technologists-for-progress/52calls-52weeks/commit/5f73394c7dbd0b29fea5c907e2b815207129688c introduces some initial mailchimp scaffolding, which assumes that when you run `serverless deploy --stage dev` you have a few environment variables.  I've been `source .env`'ing the following two variables for local development, but I suppose I should start looking at CI so we can have something continuous to iterate on.
```bash
export MAILCHIMP_API=<redacted>
# MAILCHIMP *web* ID 51229 maps to...
export MAILCHIMP_LIST_ID=e3efe7e0ae
```
