### ISSUE TITLE
Add opengraph/twitter/other preview tile headers

### ISSUE THREAD

**Issue by sethvoltz** [technologists-for-progress/52calls-52weeks#24]
Services like Twitter, Facebook, iMessage, and others use these headers to provide a preview image, basic information, a small blurb and other information to users when they share links. There are a well-defined set of headers which specify information for generic purposes as well as specific service hooks.

**Comment by daybowbow** [comment]
@jontg this is the same OG image issue I was going to file. @blake213 is going to provide the OG image tonight.

**Comment by jontg** [comment]
I added [some of the metadata](github.com/technologists-for-progress/52calls-52weeks/commit/155df7a) @blake213 — feel free to update the image URL whenever you're ready!
