### ISSUE TITLE
Update to form input: Make Phone number optional 

### ISSUE THREAD

**Issue by daybowbow** [technologists-for-progress/52calls-52weeks#40]

**Comment by jontg** [comment]
I just verified that this is optional, but I believe there was some discussion around making this _non_-optional in the case where `both` or `SMS` were selected.

**Comment by jontg** [comment]
Turns out we had a [minor bug](https://github.com/technologists-for-progress/52calls-52weeks/commit/09da7bb92f2a29bb73526ff438d7aaf85e375073), which I fixed in staging.  We'll cut another release tomorrow morning once we finish the current batch of changes.
