### ISSUE TITLE
og image needs to be compressed + og description set

### ISSUE THREAD

**Issue by daybowbow** [technologists-for-progress/52calls-52weeks#55]
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fcallsforchange.com%2F

Image Unavailable
Provided og:image, https://www.callsforchange.com/assets/images/og.png could not be downloaded because it exceeded the maximum allowed sized of 8Mb or your server was too slow to respond.

The 'og:description' property should be explicitly provided, even if a value can be inferred from other tags.

**Comment by daybowbow** [comment]
@jontg this one is done, right?

**Comment by jontg** [comment]
Yep!
