### ISSUE TITLE
P1 - if Email selected as preferred contact, email address field should error if not a real email address

### ISSUE THREAD

**Issue by daybowbow** [technologists-for-progress/52calls-52weeks#61]
Error message: Please enter a valid email address
-basic test should ensure that it has X@Y.Z - currently can just enter X and have it register success
-email also should not be required if user chooses Text

**Comment by jontg** [comment]
Addressed in https://github.com/technologists-for-progress/52calls-52weeks/pull/64 — yay!  waiting on review and approval to close.
