### ISSUE TITLE
p2 - Polish: tighten up the top of the page 

### ISSUE THREAD

**Issue by daybowbow** [technologists-for-progress/52calls-52weeks#79]
Tighten up top of the page so the hero copy/signup form are above the fold on most desktop monitors - when we do this let’s make sure it doesn’t impact mobile / tablet negatively

**Comment by blake213** [comment]
Fixed here: https://github.com/technologists-for-progress/callsforchange/commit/28aa525b3bf4b6ecfb3525cab60c748b73b1ee43
