### ISSUE TITLE
Auto-rotate SSL Certificates

### ISSUE THREAD

**Issue by jontg** [technologists-for-progress/52calls-52weeks#9]
Register and auto-rotate cert via LetsEncrypt using https://certbot.eff.org/#pip-other or https://github.com/ubergeek42/lambda-letsencrypt ?

**Comment by sethvoltz** [comment]
Also, initial registration can be done via https://zerossl.com/

**Comment by jontg** [comment]
This only applies for api.52calls-52weeks.com and api.callsforchange.com

**Comment by jontg** [comment]
Resolved by using the new functionality provided by Amazon Certificate Manager:
```
ACM automatically handles renewal of certificates it issues. You do not need to rotate any ACM-issued certificates for your custom domain names. CloudFront handles it on your behalf.```
